name = "SimpleNavierStokes"
uuid = "4bf8ea9e-95b0-4583-ac5a-fb05804bca69"
authors = ["emad <emad@vt.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.5"
